Repository rollkit/docs, pull requests merged in 2023-08, with the labels that each got.

#213 Fix github raw user content links
  tutorials/cosmwasm.md
  tutorials/gm-world.md
  tutorials/recipe-book.md
  tutorials/wordle.md
Labels: bug

#222 add banner to show site is under construction
  .vitepress/theme/index.ts
  .vitepress/theme/style.css
Labels: documentation, enhancement, style

#218 set path to title of page to remove "Rollkit | Rollkit" from home page title
  .vitepress/config.ts
Labels: enhancement, style

#217 docs: add btc tutorial
  tutorials/bitcoin.md
Labels: documentation

#216 update versions to v0.10.2 compatibility
  .vitepress/config.ts
  blog/introducing-rollkit.md
  reference/building-with-rollkit.md
  reference/stack.md
  scripts/gm/init-full-node.sh
  scripts/gm/init-local.sh
  tutorials/block-times.md
  tutorials/cosmwasm.md
  tutorials/full-and-sequencer-node.md
  tutorials/gm-world.md
  tutorials/lazy-sequencing.md
  tutorials/recipe-book.md
  tutorials/starter-rollup.md
  tutorials/wordle.md
Labels: documentation

#241 docs: fix FN + SN setup, deprecate gateway, use programmatic auth token
  scripts/gm/init-full-node.sh
  scripts/gm/init-local.sh
  tutorials/full-and-sequencer-node.md
  tutorials/gm-world.md
Labels: bug, documentation

#245 fix: favicon, light mode version only
  .vitepress/config.ts
Labels: bug, style
